spring:
  datasource:
    url: jdbc:postgresql://solely-exemplary-primate.data-1.use1.tembo.io:5432/estoque-inteligente
    username: postgres
    password: ${SENHA}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
